# Generated by Django 5.2.16 on 2026-07-17 18:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagnie_aerienne', models.CharField(max_length=100)),
                ('numero_vol', models.CharField(max_length=20)),
                ('description', models.TextField()),
                ('priorite', models.CharField(choices=[('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3'), ('P4', 'P4'), ('P5', 'P5')], max_length=2)),
                ('statut', models.CharField(choices=[('ouvert', 'Ouvert'), ('affecte', 'Affecté'), ('en_cours', 'En cours de traitement'), ('escalade', 'Escaladé'), ('resolu', 'Résolu'), ('cloture', 'Clôturé')], default='ouvert', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('commentaire_cloture', models.TextField(blank=True)),
                ('assigne_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assignes', to=settings.AUTH_USER_MODEL)),
                ('cree_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_crees', to=settings.AUTH_USER_MODEL)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.equipement')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='core.zone')),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('ancien_statut', models.CharField(blank=True, max_length=20)),
                ('nouveau_statut', models.CharField(blank=True, max_length=20)),
                ('commentaire', models.TextField(blank=True)),
                ('date_action', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique', to='incidents.ticket')),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_action'],
            },
        ),
    ]
